version: '3.8'

services:
  postgres_db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'users'
      POSTGRES_PASSWORD: 'password'

  redis_cache:
    image: redis
    ports:
      - '6379:6379'
    environment:
      REDIS_HOST: 'localhost'
